<?php
// autogenerated file 30.08.2007 09:37
// $Id$
// $Log$
//
require_once 'EbatNs_ComplexType.php';

class BrandMPNType extends EbatNs_ComplexType
{
	// start props
	// @var string $Brand
	var $Brand;
	// @var string $MPN
	var $MPN;
	// end props

/**
 *

 * @return string
 */
	function getBrand()
	{
		return $this->Brand;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBrand($value)
	{
		$this->Brand = $value;
	}
/**
 *

 * @return string
 */
	function getMPN()
	{
		return $this->MPN;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setMPN($value)
	{
		$this->MPN = $value;
	}
/**
 *

 * @return 
 */
	function BrandMPNType()
	{
		$this->EbatNs_ComplexType('BrandMPNType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Brand' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'MPN' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
