<?php
// autogenerated file 30.08.2007 09:37
// $Id$
// $Log$
//
require_once 'EbatNs_ComplexType.php';

class ReturnPolicyType extends EbatNs_ComplexType
{
	// start props
	// @var string $Description
	var $Description;
	// @var string $EAN
	var $EAN;
	// @var string $Refund
	var $Refund;
	// @var token $RefundOption
	var $RefundOption;
	// $var token $ReturnsAcceptedOption
	var $ReturnsAcceptedOption;
	// $var string $ReturnsWithin
	var $ReturnsWithin;
	// $var token $ReturnsWithinOption
	var $ReturnsWithinOption;
	// end props

/**
 *

 * @return string
 */
	function getDescription()
	{
		return $this->Description;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDescription($value)
	{
		$this->Description = $value;
	}
/**
 *

 * @return string
 */
	function getEAN()
	{
		return $this->EAN;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEAN($value)
	{
		$this->EAN = $value;
	}
/**
 *

 * @return string
 */
	function getRefund()
	{
		return $this->Refund;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setRefund($value)
	{
		$this->Refund = $value;
	}
/**
 *

 * @return token
 */
	function getRefundOption()
	{
		return $this->RefundOption;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setRefundOption($value)
	{
		$this->RefundOption = $value;
	}
/**
 *

 * @return token
 */
	function getReturnsAcceptedOption()
	{
		return $this->ReturnsAcceptedOption;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setReturnsAcceptedOption($value)
	{
		$this->ReturnsAcceptedOption = $value;
	}
/**
 *

 * @return token
 */
	function getReturnsWithinOption()
	{
		return $this->ReturnsWithinOption;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setReturnsWithinOption($value)
	{
		$this->ReturnsWithinOption = $value;
	}
/**
 *

 * @return string
 */
	function getReturnsWithin()
	{
		return $this->ReturnsWithin;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setReturnsWithin($value)
	{
		$this->ReturnsWithin = $value;
	}
/**
 *

 * @return 
 */
	function ReturnPolicyType()
	{
		$this->EbatNs_ComplexType('ReturnPolicyType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Description' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'EAN' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Refund' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'RefundOption'=>array(
					'required' => false,
					'type' => 'token',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ReturnsAcceptedOption'=>array(
					'required' => true,
					'type' => 'token',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ReturnsWithinOption'=>array(
					'required' => true,
					'type' => 'token',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ReturnsWithin'=>array(
					'required' => true,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
			));

	}
}
?>
